'use strict';                                                                   //Switch to errors only

module.exports = {
  0x50: 'Standard Message Received',
  0x51: 'Extended Message Received',
  0x52: 'X10 Received',
  0x53: 'ALL-Linking Completed',
  0x54: 'Button Event Report',
  0x55: 'User Reset Detected',
  0x56: 'ALL-Link Cleanup Failure Report',
  0x57: 'ALL-Link Record Response',
  0x58: 'ALL-Link Cleanup Status Report',
  0x60: 'Get IM Info',
  0x61: 'Send ALL-Link Command',
  0x62: 'Send INSTEON Message',
  0x63: 'Send X10',
  0x64: 'Start ALL-Linking',
  0x65: 'Cancel ALL-Linking',
  0x66: 'Set Host Device Category',
  0X67: 'Reset the IM',
  0x68: 'Set ACK Message Byte',
  0x69: 'Get First ALL-Link Record',
  0x6A: 'Get Next ALL-Link Record ',
  0x6B: 'Set IM Configuration',
  0x6C: 'Get ALL-Link Record for Sender',
  0x6D: 'LED On',
  0x6E: 'LED Off',
  0X6F: 'Manage ALL-Link Record',
  0x70: 'Set NAK Message Byte',
  0x71: 'Set ACK Message Two Bytes',
  0x72: 'RF Sleep',
  0x73: 'Get IM Configuration',
};
